name: Release

on:
  release:
    types: [published]

jobs:
  release:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools twine wheel
    - name: Build release ${{ github.event.release.tag_name }}
      env:
        MEG_RUNTIME_PKG_VERSION: ${{ github.event.release.tag_name }}
      run: |
        python setup.py sdist bdist_wheel
    - name: Twine check
      run: |
        twine check dist\*
    - name: Upload source distribution for release ${{ github.event.release.tag_name }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist\meg_runtime-${{ github.event.release.tag_name }}.tar.gz
        asset_name: meg_runtime-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip
    - name: Upload wheel distribution for release ${{ github.event.release.tag_name }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist\meg_runtime-${{ github.event.release.tag_name }}-py3-none-any.whl
        asset_name: meg_runtime-${{ github.event.release.tag_name }}-py3-none-any.whl
        asset_content_type: application/zip
    - name: Publish release ${{ github.event.release.tag_name }} to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_NON_INTERACTIVE: 1
      run: |
        twine upload dist\*
